version: '3.8'

services:
  api:
    build: .
    container_name: monitorup-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database_psgrts:5432/${POSTGRES_DB}
    depends_on:
      - redis_cache
      - database_psgrts

  prometheus:
    image: prom/prometheus:latest
    container_name: monitorup-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: monitorup-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitorup-cadvisor
    ports:
      - "8081:8080"          
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    devices:
      - /dev/kmsg

  node_exporter:
    image: prom/node-exporter:latest
    container_name: monitorup-node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro



  redis_cache:
    image: redis:alpine
    container_name: monitorup-redis
    ports:
      - "6379:6379"

  database_psgrts:
    image: postgres:15-alpine
    container_name: monitorup-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database_psgrts:5432/${POSTGRES_DB}
    depends_on:
      - redis_cache
      - database_psgrts

  beat:
    build: .
    command: celery -A celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database_psgrts:5432/${POSTGRES_DB}
    depends_on:
      - redis_cache
      - database_psgrts


volumes:
  postgres_data:
