apiVersion: v1
kind: Secret
metadata:
  name: monitorup-config
type: Opaque
stringData:
  SECRET_KEY: "dev-secret-troque-em-prod"
  ALGORITHM: "HS256"
  ORIGINS: "*"
  POSTGRES_USER: "monitorup"
  POSTGRES_PASSWORD: "monitorup_pass"
  POSTGRES_DB: "monitorup"
  DATABASE_URL: "postgresql://monitorup:monitorup_pass@postgres:5432/monitorup"
  REDIS_URL: "redis://redis:6379/0"
