"""initial

Revision ID: 6899f7f27e3a
Revises: e0a5cd8178d4
Create Date: 2026-01-13 18:20:22.833522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '6899f7f27e3a'
down_revision: Union[str, Sequence[str], None] = 'e0a5cd8178d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cadastro', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'cadastro', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cadastro', type_='unique')
    op.drop_column('cadastro', 'email')
    # ### end Alembic commands ###
