"""verify and index

Revision ID: 9f10470cf155
Revises: 62dbd1e199fb
Create Date: 2026-06-26 01:11:39.442736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f10470cf155'
down_revision: Union[str, Sequence[str], None] = '62dbd1e199fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_monitor_user_id'), 'monitor', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_constraint(op.f('user_user_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_user_key'), 'user', ['user'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'is_verified')
    op.drop_index(op.f('ix_monitor_user_id'), table_name='monitor')
    # ### end Alembic commands ###
